backend:
  name: git-gateway
  branch: master
media_library:
  name: cloudinary
  config:
    cloud_name: damienvdw
    api_key: 695141127517874
    default_transformations:
      - - fetch_format: auto
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "recettes" # Used in routes, e.g., /admin/collections/blog
    label: "Recette" # Used in the UI
    folder: "content/recettes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", allow_multiple: false}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Service", name: "service", widget: "select", options: ["Entrées", "Plats principaux", "Desserts", "Autre"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}